name:                streaming-archive
version:             0.1.0.0
github:              "deepflowinc/streaming-archive"
license:             BSD-3-Clause
author:              "DeepFlow, Inc."
maintainer:          "DeepFlow, Inc."
copyright:           "2024 (c) DeepFlow, Inc."

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Utilities for streaming package to manipulate archive formats, including (us)tar, Zip, and LZMA (`.xz`)..
category:            streaming, Codec, compression

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/deepflowinc/streaming-archive#readme>

dependencies:
- base >= 4.7 && < 5

language: GHC2021
default-extensions:
- DuplicateRecordFields
- NoFieldSelectors
- OverloadedLabels
- OverloadedRecordDot

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wunused-packages

library:
  source-dirs: src
  dependencies:
  - attoparsec
  - bytestring
  - comonad
  - conduit
  - filepath
  - foldl
  - generic-lens
  - lens
  - lzma
  - primitive
  - safe-exceptions
  - streaming
  - streaming-attoparsec
  - streaming-bytestring
  - text
  - time
  - transformers
  - unliftio
  - zip-stream
