name:                streaming-s3
version:             0.1.0.0
github:              "deepflowinc/streaming-s3"
license:             BSD-3-Clause
author:              "DeepFlow, Inc."
maintainer:          "DeepFlow, Inc."
copyright:           "2024 (c) DeepFlow, Inc."

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/deepflowinc/streaming-s3#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wunused-packages

library:
  source-dirs: src
  dependencies:
  - lens
  - transformers
  - aeson
  - bytestring
  - case-insensitive
  - streaming
  - streaming-bytestring
  - streaming-SHA
  - streaming-http
  - generic-lens
  - unordered-containers
  - containers
  - semigroupoids
  - text
  - time
  - http-client
  - http-conduit
  - streaming-http
  - http-types
  - network-uri
